version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: nginx
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        ports:
            - 8000:80
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        networks:
            - frontend
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php
        env_file:
            - .env
        volumes:
            - ./docker/php/config.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
            - ./public:/var/www/html/public
            - ./src:/var/www/html/src
            - ./views:/var/www/html/views
        restart: always
        networks:
            - frontend
            - backend

    mysql:
        build: ./docker/mysql
        container_name: mysql
        env_file:
            - .env
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./docs/database.sql:/docker-entrypoint-initdb.d/database.sql
            - db-data:/var/lib/mysql
        restart: always
        networks:
            - backend

volumes:
    db-data:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge